run:
  timeout: 5m
  issues-exit-code: 1
  tests: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - exhaustive
    - copyloopvar
    - gocritic
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - wastedassign

issues:
  max-same-issues: 0
  exclude-rules:
    - linters:
        - gocritic
      text: "appendAssign"
    - path: _test\.go
      linters:
        - errcheck
        - revive
        - gosec
  exclude:
    - "unhandled-error: Unhandled error in call to function strBld.Write.+"
    - "unhandled-error: Unhandled error in call to function strings.Builder..+"
    - "unhandled-error: Unhandled error in call to function fmt..+"

linters-settings:
  goimports:
    local-prefixes: github.com/aisbergg/go-unidecode

  gofumpt:
    extra-rules: true

  revive:
    ignore-generated-header: true
    severity: "warning"
    confidence: 0.8
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: empty-lines
        disabled: true
      - name: blank-imports
        disabled: true
      - name: file-header
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: banned-characters
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: cognitive-complexity
        disabled: true

      - name: argument-limit
        arguments: [5]
      - name: function-result-limit
        arguments: [3]

  exhaustive:
    check: [switch, map]
    default-signifies-exhaustive: false
