version: "2"

run:
  timeout: 5m
  tests: false

output:
  formats:
    text:
      path: stdout

issues:
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/aisbergg/go-bruh

    gofumpt:
      extra-rules: true

    golines:
      max-len: 120


linters:
  default: standard
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - exhaustive
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - wastedassign

  exclusions:
    paths:
      - 'playground'
      - 'internal/table/x.*\.go$'

  settings:
    revive:
      severity: "warning"
      confidence: 0.8
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: empty-lines
          disabled: true
        - name: blank-imports
          disabled: true
        - name: file-header
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: banned-characters
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: cognitive-complexity
          disabled: true

        - name: argument-limit
          arguments: [5]
        - name: function-result-limit
          arguments: [3]

    exhaustive:
      check: [switch, map]
      default-signifies-exhaustive: false

    errcheck:
      exclude-functions:
        - fmt.Fprintln
        # - (*github.com/aisbergg/go-bruh/internal/stringbuilder.StringBuilder).WriteByte

    gosec:
      excludes:
        # - G104  #
        - G103 # Use of unsafe calls should be audited
