package table

var x1f1 = []string{
	"0.",          // 0x00
	"0,",          // 0x01
	"1,",          // 0x02
	"2,",          // 0x03
	"3,",          // 0x04
	"4,",          // 0x05
	"5,",          // 0x06
	"6,",          // 0x07
	"7,",          // 0x08
	"8,",          // 0x09
	"9,",          // 0x0a
	"\uffff",      // 0x0b
	"\uffff",      // 0x0c
	"\uffff",      // 0x0d
	"\uffff",      // 0x0e
	"\uffff",      // 0x0f
	"(A)",         // 0x10
	"(B)",         // 0x11
	"(C)",         // 0x12
	"(D)",         // 0x13
	"(E)",         // 0x14
	"(F)",         // 0x15
	"(G)",         // 0x16
	"(H)",         // 0x17
	"(I)",         // 0x18
	"(J)",         // 0x19
	"(K)",         // 0x1a
	"(L)",         // 0x1b
	"(M)",         // 0x1c
	"(N)",         // 0x1d
	"(O)",         // 0x1e
	"(P)",         // 0x1f
	"(Q)",         // 0x20
	"(R)",         // 0x21
	"(S)",         // 0x22
	"(T)",         // 0x23
	"(U)",         // 0x24
	"(V)",         // 0x25
	"(W)",         // 0x26
	"(X)",         // 0x27
	"(Y)",         // 0x28
	"(Z)",         // 0x29
	"<S>",         // 0x2a
	"(C)",         // 0x2b
	"(R)",         // 0x2c
	"\uffff",      // 0x2d
	"\uffff",      // 0x2e
	"\uffff",      // 0x2f
	"[A]",         // 0x30
	"[B]",         // 0x31
	"[C]",         // 0x32
	"[D]",         // 0x33
	"[E]",         // 0x34
	"[F]",         // 0x35
	"[G]",         // 0x36
	"[H]",         // 0x37
	"[I]",         // 0x38
	"[J]",         // 0x39
	"[K]",         // 0x3a
	"[L]",         // 0x3b
	"[M]",         // 0x3c
	"[N]",         // 0x3d
	"[O]",         // 0x3e
	"[P]",         // 0x3f
	"[Q]",         // 0x40
	"[R]",         // 0x41
	"[S]",         // 0x42
	"[T]",         // 0x43
	"[U]",         // 0x44
	"[V]",         // 0x45
	"[W]",         // 0x46
	"[X]",         // 0x47
	"[Y]",         // 0x48
	"[Z]",         // 0x49
	"\uffff",      // 0x4a
	"\uffff",      // 0x4b
	"\uffff",      // 0x4c
	"\uffff",      // 0x4d
	"\uffff",      // 0x4e
	"\uffff",      // 0x4f
	"(A)",         // 0x50
	"(B)",         // 0x51
	"(C)",         // 0x52
	"(D)",         // 0x53
	"(E)",         // 0x54
	"(F)",         // 0x55
	"(G)",         // 0x56
	"(H)",         // 0x57
	"(I)",         // 0x58
	"(J)",         // 0x59
	"(K)",         // 0x5a
	"(L)",         // 0x5b
	"(M)",         // 0x5c
	"(N)",         // 0x5d
	"(O)",         // 0x5e
	"(P)",         // 0x5f
	"(Q)",         // 0x60
	"(R)",         // 0x61
	"(S)",         // 0x62
	"(T)",         // 0x63
	"(U)",         // 0x64
	"(V)",         // 0x65
	"(W)",         // 0x66
	"(X)",         // 0x67
	"(Y)",         // 0x68
	"(Z)",         // 0x69
	"\uffff",      // 0x6a
	"\uffff",      // 0x6b
	"\uffff",      // 0x6c
	"\uffff",      // 0x6d
	"\uffff",      // 0x6e
	"\uffff",      // 0x6f
	"[A]",         // 0x70
	"[B]",         // 0x71
	"[C]",         // 0x72
	"[D]",         // 0x73
	"[E]",         // 0x74
	"[F]",         // 0x75
	"[G]",         // 0x76
	"[H]",         // 0x77
	"[I]",         // 0x78
	"[J]",         // 0x79
	"[K]",         // 0x7a
	"[L]",         // 0x7b
	"[M]",         // 0x7c
	"[N]",         // 0x7d
	"[O]",         // 0x7e
	"[P]",         // 0x7f
	"[Q]",         // 0x80
	"[R]",         // 0x81
	"[S]",         // 0x82
	"[T]",         // 0x83
	"[U]",         // 0x84
	"[V]",         // 0x85
	"[W]",         // 0x86
	"[X]",         // 0x87
	"[Y]",         // 0x88
	"[Z]",         // 0x89
	"\uffff",      // 0x8a
	"\uffff",      // 0x8b
	"\uffff",      // 0x8c
	"\uffff",      // 0x8d
	"\uffff",      // 0x8e
	"\uffff",      // 0x8f
	"DJ",          // 0x90
	"[CL]",        // 0x91
	"[COOL]",      // 0x92
	"[FREE]",      // 0x93
	"[ID]",        // 0x94
	"[NEW]",       // 0x95
	"[NG]",        // 0x96
	"[OK]",        // 0x97
	"[SOS]",       // 0x98
	"[UP!]",       // 0x99
	"[VS]",        // 0x9a
	"[3D]",        // 0x9b
	"[2nc-Scr]",   // 0x9c
	"[2K]",        // 0x9d
	"[4K]",        // 0x9e
	"[8K]",        // 0x9f
	"[5.1]",       // 0xa0
	"[7.1]",       // 0xa1
	"[22.2]",      // 0xa2
	"[60P]",       // 0xa3
	"[120P]",      // 0xa4
	"[d]",         // 0xa5
	"[HC]",        // 0xa6
	"[HDR]",       // 0xa7
	"[Hi-res]",    // 0xa8
	"[Loss-less]", // 0xa9
	"[SHV]",       // 0xaa
	"[UHD]",       // 0xab
	"[VOD]",       // 0xac
	"(m)",         // 0xad
	"\uffff",      // 0xae
	"\uffff",      // 0xaf
	"\uffff",      // 0xb0
	"\uffff",      // 0xb1
	"\uffff",      // 0xb2
	"\uffff",      // 0xb3
	"\uffff",      // 0xb4
	"\uffff",      // 0xb5
	"\uffff",      // 0xb6
	"\uffff",      // 0xb7
	"\uffff",      // 0xb8
	"\uffff",      // 0xb9
	"\uffff",      // 0xba
	"\uffff",      // 0xbb
	"\uffff",      // 0xbc
	"\uffff",      // 0xbd
	"\uffff",      // 0xbe
	"\uffff",      // 0xbf
	"\uffff",      // 0xc0
	"\uffff",      // 0xc1
	"\uffff",      // 0xc2
	"\uffff",      // 0xc3
	"\uffff",      // 0xc4
	"\uffff",      // 0xc5
	"\uffff",      // 0xc6
	"\uffff",      // 0xc7
	"\uffff",      // 0xc8
	"\uffff",      // 0xc9
	"\uffff",      // 0xca
	"\uffff",      // 0xcb
	"\uffff",      // 0xcc
	"\uffff",      // 0xcd
	"\uffff",      // 0xce
	"\uffff",      // 0xcf
	"\uffff",      // 0xd0
	"\uffff",      // 0xd1
	"\uffff",      // 0xd2
	"\uffff",      // 0xd3
	"\uffff",      // 0xd4
	"\uffff",      // 0xd5
	"\uffff",      // 0xd6
	"\uffff",      // 0xd7
	"\uffff",      // 0xd8
	"\uffff",      // 0xd9
	"\uffff",      // 0xda
	"\uffff",      // 0xdb
	"\uffff",      // 0xdc
	"\uffff",      // 0xdd
	"\uffff",      // 0xde
	"\uffff",      // 0xdf
	"\uffff",      // 0xe0
	"\uffff",      // 0xe1
	"\uffff",      // 0xe2
	"\uffff",      // 0xe3
	"\uffff",      // 0xe4
	"\uffff",      // 0xe5
	"\uffff",      // 0xe6
	"\uffff",      // 0xe7
	"\uffff",      // 0xe8
	"\uffff",      // 0xe9
	"\uffff",      // 0xea
	"\uffff",      // 0xeb
	"\uffff",      // 0xec
	"\uffff",      // 0xed
	"\uffff",      // 0xee
	"\uffff",      // 0xef
	"\uffff",      // 0xf0
	"\uffff",      // 0xf1
	"\uffff",      // 0xf2
	"\uffff",      // 0xf3
	"\uffff",      // 0xf4
	"\uffff",      // 0xf5
	"\uffff",      // 0xf6
	"\uffff",      // 0xf7
	"\uffff",      // 0xf8
	"\uffff",      // 0xf9
	"\uffff",      // 0xfa
	"\uffff",      // 0xfb
	"\uffff",      // 0xfc
	"\uffff",      // 0xfd
	"\uffff",      // 0xfe
	"\uffff",      // 0xff
}
